$quote "
$delset 049
$set    049 German language
 
$ Labels and buttons
 
  1 "Schri~ftart:"
  2 "G~rî·e:"
  3 "~Zeichensatz:"
  4 "~Lîschen"
  5 "~öber"
  6 "~Def."
 
$ States
 
 20 "Laden..."
 21 "Darstellung der Schriftart..."
 22 "Voraussetzungen fÅr Schriftart erfÅllt"
 23 "ASCII-Zeichen %u (hex: %02X) ausgewÑhlt"
 24 "ASCII-Zeichen %u (hex: %02X) in Zwischenablage kopiert"
 25 "Zwischenablage erfolgreich gelîscht"
 
$ Others
 
 40 "Umri·"
 41 "System"
 
$ Context menu items
 
 50 "Zeichen in Zwischen~ablage kopieren\tEnter"
 51 "Zwischenablage ~lîschen\tDel"
 52 "Schriftart~definitionen\tCtrl-S"
 53 "~RTF-UnterstÅtzung aktivieren"
 54 "~Schlie·en\tAlt-F4"
 
$ Font specifications
 
 60 "Schrift"
 61 "Familie"
 62 "ZeichensÑtze"
    63 "Alle"
    64 "Keiner"
 65 "Schnitt"
    66 "Ultramager"
    67 "Extramager"
    68 "Mager"
    69 "Halbmager"
    70 "Medium (normal)"
    71 "Halbfett"
    72 "Fett"
    73 "Extrafett"
    74 "Ultrafett"
    75 "Unbekannt"
 76 Breitentyp
    77 "Ultraeng"
    78 "Eng"
    79 "Schmal"
    80 "Halbschmal"
    81 "Medium (normal)"
    82 "Halbbreit"
    83 "Breit"
    84 "Extrabreit"
    85 "Ultrabreit"
    86 "Unbekannt"
 87 "Minimale Punktgrî·e"
 88 "Nominale Punktgrî·e"
 89 "Maximale Punktgrî·e"
 90 "Auflîsung"
