$quote "
$delset 001
$set    001 English language

$ Labels and buttons

  1 "~Font:"
  2 "Si~ze:"
  3 "~Codepage:"
  4 "C~lear"
  5 "~About"
  6 "~Specs"

$ States

 20 "Loading..."
 21 "Rendering font..."
 22 "Font requirements matched successfully"
 23 "ASCII %u character (hex: %02X) selected"
 24 "ASCII %u character (hex: %02X) added to clipboard"
 25 "Clipboard cleared successfully"

$ Others

 40 "outline"
 41 "system"

$ Context menu items

 50 "~Add character to clipboard\tEnter"
 51 "C~lear clipboard\tDel"
 52 "Font ~Specifications\tCtrl-S"
 53 "~Enable RTF support"
 54 "~Close\tAlt-F4"

$ Font specifications

 60 "Font"
 61 "Family"
 62 "Codepages"
    63 "All"
    64 "None"
 65 "Weight class"
    66 "Ultra-light"
    67 "Extra-light"
    68 "Light"
    69 "Semi-light"
    70 "Medium (normal)"
    71 "Semi-bold"
    72 "Bold"
    73 "Extra-bold"
    74 "Ultra-bold"
    75 "Unknown"
 76 Width Class
    77 "Ultra-condensed"
    78 "Extra-condensed"
    79 "Condensed"
    80 "Semi-condensed"
    81 "Medium (normal)"
    82 "Semi-expanded"
    83 "Expanded"
    84 "Extra-expanded"
    85 "Ultra-expanded"
    86 "Unknown"
 87 "Minimal Point Size"
 88 "Nominal Point Size"
 89 "Maximal Point Size"
 90 "Resolution"
